#!/bin/sh
# ============================================================================
# clean_all.sh  --  remove everything generated by run_all.sh, restoring the
# committed source tree.
#
# REMOVES (outputs / intermediates):
#   - stage 1: BEN_*.NEW.csv, BEN_*.NORMED.csv, assembled_metrics.txt, and the
#     bulky extras ward_medoid_ccbs_v4 writes into full_w1.0/ward_xde_2745/
#     (cc_sub.npy, Z_ward.npy, medoid_analysis_k100.xlsx, *.png, sem_sc_*, ...)
#   - stage 2: master_/extra_/sem_best_lp_/consolidated *.xlsx, figures_2745/,
#     the files written into ward_sem_clean2_k120/, and Step*.log
#   - also any from-raw (0000_Run_USCounty) outputs if present
#
# KEEPS (committed inputs -- run_standard still works after cleaning):
#   - full_w1.0/metric_x_death_cc_1.0_0.csv, full_w1.0/full_cc_ase0_p=1.0_0.csv
#   - full_w1.0/ward_xde_2745/{Z_med_xde100.npy, medoid_list_xde100.json,
#     xde100_reps.csv, xde100_assignments.csv}
#   - ward_sem_clean2_k120/ curated inputs, data/, code/, and config files
#   (run_all overwrites the full_w1.0 CC files in place; they are part of the
#    repo, so clean_all leaves them. Re-run derive_w1.0_cc.sh to rebuild them.)
#
# Usage:
#   sh code/clean_all.sh            # remove generated outputs
#   sh code/clean_all.sh --dry-run  # just list what would be removed
# ============================================================================
set -u
cd "$(dirname "$0")/.." || exit 1
DRY=0; [ "${1:-}" = "--dry-run" ] && DRY=1
rm_(){ [ -e "$1" ] || return 0; if [ "$DRY" = 1 ]; then echo "  would rm  $1"; else rm -rf -- "$1"; fi; }

echo "=== clean_all${DRY:+ (dry-run)}: removing run_all.sh outputs ==="

# ---- stage 1 (derive_w1.0_cc.sh) ----
rm_ BEN_MERGED_MEASURES_imputed_20s_v1.31.GG.Add2024.NEW.csv
rm_ BEN_MERGED_MEASURES_imputed_20s_v1.31.GG.Add2024.NORMED.csv
rm_ assembled_metrics.txt
# extras written into full_w1.0/ward_xde_2745/ -- keep only the 4 curated inputs
KEEP_XDE="Z_med_xde100.npy medoid_list_xde100.json xde100_reps.csv xde100_assignments.csv"
for p in full_w1.0/ward_xde_2745/*; do
  [ -e "$p" ] || continue; b=$(basename "$p"); keep=0
  for k in $KEEP_XDE; do [ "$b" = "$k" ] && keep=1 && break; done
  [ "$keep" = 1 ] || rm_ "$p"
done

# ---- stage 2 (run_standard_k120_w1.0.sh) ----
rm_ master_sem_clusters_clean2_k120_w1.0.xlsx
rm_ extra_tables_clean2_k120_w1.0.xlsx
rm_ sem_best_lp_clean2_k120_w1.0.xlsx
rm_ SCE_paper_tables_consolidated_clean2_k120_w1.0.xlsx
rm_ figures_2745

# ---- Spearman sensitivity (run_spearman.sh / make_spearman_comparison.py) ----
rm_ figures_2745_spearman
rm_ spearman_results
rm_ SCE_Pearson_vs_Spearman_supplement.xlsx
for f in master_sem_clusters_clean2_k120_w1.0_spearman.xlsx extra_tables_clean2_k120_w1.0_spearman.xlsx \
         sem_best_lp_clean2_k120_w1.0_spearman.xlsx SCE_paper_tables_consolidated_clean2_k120_w1.0_spearman.xlsx; do rm_ "$f"; done
# ---- vintage figure (vintage_cc_continuous.py) ----
rm_ Supplementary_Tables_Figures
# files written into ward_sem_clean2_k120/ -- keep only the 7 curated inputs
KEEP_SEM="ward_sem_metrics.csv sem100_labels.csv sc_label_embeddings.npy Z_med_sem100.npy medoid_list_sem100.json ward_sem_reps.csv README_pipeline.md"
for p in ward_sem_clean2_k120/*; do
  [ -e "$p" ] || continue; b=$(basename "$p"); keep=0
  for k in $KEEP_SEM; do [ "$b" = "$k" ] && keep=1 && break; done
  [ "$keep" = 1 ] || rm_ "$p"
done

# ---- step logs (both stages) ----
for f in Step*.log; do rm_ "$f"; done
rm_ pipeline_run.log

# ---- python bytecode caches ----
for d in $(find . -name '__pycache__' -type d 2>/dev/null); do rm_ "$d"; done

# ---- from-raw (0000_Run_USCounty-v10.1.sh) outputs, if present ----
rm_ ward_sem_2745
rm_ ward_xde_2745
rm_ lp_sensitivity_sweep
for f in metric_x_death_cc_0.0_25.1.csv metric_x_death_cc_0.0_25.1.metrics \
         "full_cc_ase0_p=0.0_25.1.csv" cc_histograms_25.1.png cc_histograms_T_25.1.png \
         despair_cc_trajectory.png despair_lp_lt65.png fig_xde_sem_overlap.png \
         sem_best_lp_2745.xlsx master_sem_clusters_2745.xlsx extra_tables_sem_2745.xlsx; do
  rm_ "$f"
done

echo "=== done ==="
